[package]
name="tcp"
version = "0.1.0"
authors = ["Utkarsh <projects.utkarshMaurya@gmail.com>"]
edition = "2021"

[dependencies]
tun-tap = "0.1.4"
# TODO: implement your own ip parser, till then use this crate
etherparse = '0.19.0'
